### ISSUE TITLE
Change color to xAxis label

### ISSUE THREAD

**Issue by pinkynrg** [whawker/react-jsx-highcharts#114]
before I used to do: 

```json
"xAxis": {
    "label": {
        "color": "#d8d9da"
    },
},
```
How do I change now the color of the label by passing props? It seems like there is no XAxis.Label component. Should I pass some props directly to XAxis component? What would the format be?

**Comment by whawker** [comment]
Unfortunately, this is one of the occasions where we need to pass in a configuration object .

We should investigate how best to extract this as a component.

[Example here](https://stackblitz.com/edit/rjh-colored-labels?file=MyChart.js)

**Comment by pinkynrg** [comment]
By the way this is the best work i've seen lately. I needed this sooooo much! Great great great work!

**Comment by pinkynrg** [comment]
I can't get the text of the legend to get colored as I want. How would you do it?

**Comment by whawker** [comment]
This is probably a good use case for using the style by CSS import by the way.

In JS
```js
import Highcharts from 'highcharts/js/highcharts'
```

CSS
```css
@import url('https://code.highcharts.com/css/highcharts.css');

.highcharts-xaxis-labels text {
  fill: red;
}

.highcharts-yaxis-labels text {
  fill: blue;
}

.highcharts-legend-item tspan {
  fill: green;
}
```

[Example here](https://stackblitz.com/edit/rjh-colored-labels-css?file=style.css)

> By the way this is the best work i've seen lately. I needed this sooooo much! Great great great work!

And thanks 😀
